version: '3.8'
services:
  web:
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
  shop-admin:
    image: shop-admin:latest
    build:
      context: .
      dockerfile: ./apps/shop-admin/Dockerfile
    ports:
      - "3001:3001"
  super-admin:
    image: super-admin:latest
    build:
      context: .
      dockerfile: ./apps/super-admin/Dockerfile
    ports:
      - "3002:3002"
  nginx:
    image: nginx-custom:latest
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - shop-admin
      - super-admin