name: shop admin build and deploy

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'

jobs:
  build_and_deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Get secrets from AWS Secrets Manager
        run: |
          echo "NEXT_PUBLIC_API_DOMAIN=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_MANAGER_SHOP_ADMIN_NAME }} --query 'SecretString' --output text | jq -r '.NEXT_PUBLIC_API_DOMAIN')" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_CLIENT_ID=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_MANAGER_SHOP_ADMIN_NAME }} --query 'SecretString' --output text | jq -r '.NEXT_PUBLIC_CLIENT_ID')" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_CLIENT_SECRET_KEY=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_MANAGER_SHOP_ADMIN_NAME }} --query 'SecretString' --output text | jq -r '.NEXT_PUBLIC_CLIENT_SECRET_KEY')" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_CAFE24_REDIRECT_URI=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.AWS_SECRET_MANAGER_SHOP_ADMIN_NAME }} --query 'SecretString' --output text | jq -r '.NEXT_PUBLIC_CAFE24_REDIRECT_URI')" >> $GITHUB_ENV

      - name: Build and push docker image
        uses: review-canvas/gh-actions/common/build/docker@main
        id: build-image-result
        with:
          repository: ${{ secrets.AWS_ECR_REPOSITORY }}
          dockerfile: ./apps/shop-admin/Dockerfile
          project: shop-admin
          extra_build_args: |
            --build-arg NEXT_PUBLIC_API_DOMAIN=${{ env.NEXT_PUBLIC_API_DOMAIN }}
            --build-arg NEXT_PUBLIC_CLIENT_ID=${{ env.NEXT_PUBLIC_CLIENT_ID }}
            --build-arg NEXT_PUBLIC_CLIENT_SECRET_KEY=${{ env.NEXT_PUBLIC_CLIENT_SECRET_KEY }}
            --build-arg NEXT_PUBLIC_CAFE24_REDIRECT_URI=${{ env.NEXT_PUBLIC_CAFE24_REDIRECT_URI }}

      - uses: review-canvas/gh-actions/deploy/ecs@main
        with:
          ecs_cluster: ${{ vars.ECS_CLUSTER }}
          service: ${{ vars.ECS_SERVICE_SHOP_ADMIN }}
          image: ${{ steps.build-image-result.outputs.image }}