name: web build and deploy

on:
  push:
    branches:
      - 'main'

jobs:
  Build:
    environment: production
    runs-on: ubuntu-latest
    outputs:
      uri: ${{ steps.encrypt.outputs.image_uri }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: false

      - name: Build and push docker image
        uses: review-canvas/gh-actions/common/build/docker@main
        id: build-image-result
        with:
          repository: ${{ secrets.AWS_ECR_REPOSITORY }}
          dockerfile: ./apps/web/Dockerfile
          project: web
      #          추후 환경변수 아래 처럼 추가
      #          extra_build_args: |
      #            --build-arg NODE_ENV=production
      #            --build-arg NODE_ENV=production

      - name: Encrypt ECR image URI
        shell: bash
        id: encrypt
        run: |
          IMAGE_URI=$(echo "${{ steps.build-image-result.outputs.image }}" | base64 -w 0)
          echo $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

  Deploy:
    needs: Build
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: false

      - name: Decrypt ECR image URI
        id: decrypt-image-uri
        shell: bash
        run: |
          echo "${{ needs.Build.outputs.uri }}"
          IMAGE_URI=$(echo ${{ needs.Build.outputs.uri }} | base64 -d)
          echo $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_OUTPUT
      

      - uses: review-canvas/gh-actions/deploy/ecs@main
        with:
          ecs_cluster: ${{ vars.ECS_CLUSTER }}
          service: ${{ vars.ECS_SERVICE_WEB }}
          image: ${{ steps.decrypt-image-uri.outputs.IMAGE_URI }}